#Expects AWS image aws/codebuild/nodejs:10.1.0
version: 0.2
env:

phases:
  install:
    #Define Runtime Version
    runtime-versions:
        nodejs: 12
    commands:
      # setup image:tag name for docker
      - export DOCKER_IMAGE_TAG=$(node -e 'let pkg=require("./package.json");console.log(`${pkg.name}:${pkg.version}`);')
      # setup docker login
      - echo => Login  to docker hub
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      # setup docker for use with aws ecr
      - echo => Setting up ECR registry for docker images...
      - export account_id="$(echo $CODEBUILD_BUILD_ARN|cut -d':' -f 5)"
      - export DOCKER_LOGIN_COMMAND="$(aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $account_id.dkr.ecr.us-east-2.amazonaws.com)"
      - export ECR_REGISTRY_URL="$account_id.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      # setup and install npm deps
      - echo => Installing NPM Dependencies
      - npm cache clean --force
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build:qa
      - echo => Tagging Docker Image...
      - docker tag $DOCKER_IMAGE_TAG $ECR_REGISTRY_URL/$DOCKER_IMAGE_TAG
      - echo => Pushing Docker Image...
      - docker push $ECR_REGISTRY_URL/$DOCKER_IMAGE_TAG
      - PACKAGE_VERSION=$(npm run version --silent)
      - echo ==> Image pushed succesfully to ECR
